name: Checkmarx Sarif Integration
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkmarx AST GitHub Action
        uses: Checkmarx/ast-github-action@main
        with:
          base_uri: https://deu.ast.checkmarx.net
          cx_tenant: cx_pm_canary_matt_slotten
          additional_params: --apikey ${{ secrets.APIKEY }} --scan-types sast,sca --report-format sarif --threshold sast-high=0
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cx_result.sarif
