name: Checkmarx AST Scan
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkmarx AST GitHub Action
        uses: Checkmarx/ast-github-action@main
        with:
          base_uri: https://deu.ast.checkmarx.net
          cx_tenant: cx_pm_canary_matt_slotten
          additional_params: --apikey ${{ secrets.API_KEY }} --report-format sarif --output-path .
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cx_result.sarif
